spring:
  profiles:
    active: ${ACTIVE_PROFILE:production}
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: '8083'

kafka-config:
  bootstrap-address: ${KAFKA_ADDRESS:54.232.4.177:19092,54.232.4.177:29092,54.232.4.177:39092}
  topic:
    name: stocks


---
spring:
  config:
    activate:
      on-profile: development
  datasource:
    username: postgres
    url: ${DB_URL:jdbc:postgresql://localhost:5432/stocks}
    password: ${DB_PASSWORD:postgres}
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      hibernate:
        ddl-auto: update

---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    username: postgres
    url: ${DB_URL:jdbc:postgresql://containers-us-west-207.railway.app:5770/stocks_broker_stocks}
    password: ${DB_PASSWORD:postgres}
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: false
      hibernate:
        ddl-auto: update